---
<%if (database) { %>
forumone::databases: 
  <%= db_name %>: 
    username: <%= db_user %>
<% } %>

forumone::webserver::vhosts:  
  vagrant: 
    path: "<%= vhost %>"

<%if (solr) { %>
forumone::solr::collections:  
  drupal: 
    order: 1
<% } %>

forumone::php::prefix: "<%= php_version %>"

forumone::ruby::version: "<%= ruby_version %>"